### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by bracesproul** [langchain-ai/open-canvas#9]
- [x] p0 [fix prompting for new artifact (initial router)](https://github.com/langchain-ai/open-canvas/issues/new)
- [x] p0 [chat interactions for editing artifacts should always apply to the open artifact](https://github.com/langchain-ai/open-canvas/issues/4)
- [x] p0 [fix UI bug where chat input is transparent](https://github.com/langchain-ai/open-canvas/issues/3)
- [x] p0 [ensure newlines are always rendered properly](https://github.com/langchain-ai/open-canvas/issues/5)
- [x] p0 [ensure highlighting always works](https://github.com/langchain-ai/open-canvas/issues/7)
- [x] p0 [ensure newest artifact is always rendered on screen](https://github.com/langchain-ai/open-canvas/issues/6)
- [x] p1 better loading state for re-generating text
- [x] p1 have artifacts generate a type (code / general writing)
- [x] p2 different action bar based on artifact type
- [x] p2 better MD renderer (allow inline editing)
- [x] p2 better code renderer (syntax highlighting, allow editing)
- [x] p1 [new thread button](https://github.com/langchain-ai/open-canvas/issues/2)
